import os
import re
import socket
from datetime import datetime, timezone

import requests
from fpdf import FPDF


# === Configuration ===
QRADAR_IP = os.getenv("QRADAR_IP", "127.0.0.1")
QRADAR_PORT = int(os.getenv("QRADAR_PORT", "514"))
ABUSEIPDB_API_KEY = os.getenv("ABUSEIPDB_API_KEY")
LISTEN_PORT = int(os.getenv("LISTEN_PORT", "5514"))
BASE_FOLDER = os.getenv("BASE_FOLDER", "ThreatReports")

if not ABUSEIPDB_API_KEY:
    raise RuntimeError(
        "ABUSEIPDB_API_KEY is not set. "
        "Set it as an environment variable before running the script."
    )

# === Extract IP address from CHECK-IP=... messages ===
IP_REGEX = re.compile(r"CHECK-IP=(\d{1,3}(?:\.\d{1,3}){3})")


def query_abuseipdb(ip):
    """Query AbuseIPDB and return normalized reputation data."""
    start_time = datetime.now()

    url = "https://api.abuseipdb.com/api/v2/check"
    headers = {
        "Key": ABUSEIPDB_API_KEY,
        "Accept": "application/json",
    }
    params = {
        "ipAddress": ip,
        "maxAgeInDays": 365,
    }

    try:
        response = requests.get(
            url,
            headers=headers,
            params=params,
            timeout=10,
        )
        response.raise_for_status()
        payload = response.json()
        data = payload["data"]
    except requests.RequestException as exc:
        raise RuntimeError(f"AbuseIPDB request failed for {ip}: {exc}") from exc
    except (KeyError, ValueError, TypeError) as exc:
        raise RuntimeError(f"Unexpected AbuseIPDB response for {ip}") from exc

    elapsed = (datetime.now() - start_time).total_seconds()
    print(f"[+] Time elapsed for {ip}: {elapsed:.3f} seconds")

    return {
        "ip": data["ipAddress"],
        "score": data["abuseConfidenceScore"],
        "country": data.get("countryCode") or "Unknown",
        "lastReportedAt": data.get("lastReportedAt") or "None",
        "totalReports": data.get("totalReports", 0),
        "elapsedTime": elapsed,
    }


def classify_status(score, total_reports):
    """Classify an IP based on AbuseIPDB confidence score."""
    if total_reports == 0:
        return "Not-Reported"
    if score >= 75:
        return "High-Risk"
    if score >= 20:
        return "Medium-Risk"
    return "Low-Risk"


def generate_pdf_report(ip, score, country, last_reported, total_reports, status):
    """Generate a PDF report for High-Risk and Medium-Risk IPs."""
    detection_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    today = datetime.now().strftime("%Y-%m-%d")

    folder = os.path.join(BASE_FOLDER, status)
    os.makedirs(folder, exist_ok=True)

    report_name = f"Report_{ip}_{today}.pdf"
    report_path = os.path.join(folder, report_name)

    now = datetime.now(timezone.utc)
    try:
        reported_time = datetime.fromisoformat(last_reported.replace("Z", "+00:00"))
        delta = now - reported_time
        hours = delta.total_seconds() / 3600
    except (AttributeError, TypeError, ValueError):
        hours = 9999

    notes = [f"This IP has been reported {total_reports} times in the past 365 days."]

    if score >= 90:
        notes.append("It has been flagged with a critical confidence score.")
    elif score >= 75:
        notes.append("This IP is highly suspicious based on abuse reports.")

    if hours < 24:
        notes.append("It was last reported within the past 24 hours.")
    elif hours < 168:
        notes.append("Recent reports within the past week indicate ongoing abuse.")
    else:
        notes.append("Not recently reported, but historical risk remains.")

    notes.append(f"Country: {country}")

    recommendations = []

    if status == "High-Risk":
        recommendations = [
            "1. Block this IP immediately on all firewalls.",
            "2. Review internal logs for past connections.",
            "3. Add to blacklists and alert the SOC team.",
            "4. Investigate for signs of compromise.",
        ]
    elif status == "Medium-Risk":
        recommendations = [
            "1. Monitor this IP for future activity.",
            "2. Correlate with existing alerts.",
            "3. Consider conditional blocking.",
            "4. Document in the threat tracking system.",
        ]

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=10)
    pdf.add_page()

    # Uses a built-in PDF font so the repository does not depend on a local Windows font path.
    pdf.set_font("Helvetica", size=12)

    pdf.cell(0, 10, txt="THREAT INTELLIGENCE REPORT", ln=True)
    pdf.cell(0, 10, txt="Generated by AbuseIPDB-QRadar Integration System", ln=True)
    pdf.cell(0, 10, txt="------------------------------------------------------------", ln=True)
    pdf.cell(0, 10, txt=f"Detection Time (UTC): {detection_time}", ln=True)
    pdf.cell(0, 10, txt=f"IP Address: {ip}", ln=True)
    pdf.cell(0, 10, txt=f"Country: {country}", ln=True)
    pdf.cell(0, 10, txt=f"Abuse Confidence Score: {score}", ln=True)
    pdf.cell(0, 10, txt=f"Last Reported At: {last_reported}", ln=True)
    pdf.cell(0, 10, txt=f"Total Reports: {total_reports}", ln=True)
    pdf.cell(0, 10, txt=f"Classification: {status}", ln=True)
    pdf.cell(0, 10, txt="------------------------------------------------------------", ln=True)

    pdf.cell(0, 10, txt="Analyst Notes:", ln=True)
    pdf.multi_cell(0, 10, txt=" ".join(notes))

    if recommendations:
        pdf.cell(0, 10, txt="------------------------------------------------------------", ln=True)
        pdf.cell(0, 10, txt="Recommendations:", ln=True)
        for line in recommendations:
            pdf.cell(0, 10, txt=line, ln=True)

    pdf.output(report_path)
    print(f"[*] PDF report saved to: {report_path}")

    return report_path


def format_syslog(result, report_path):
    """Format enriched data as an RFC 5424-style Syslog message."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    status = classify_status(result["score"], result["totalReports"])

    return (
        f"<134>1 {timestamp} AbuseIPDB-Script abuse-checker - - - AbuseIPDB-Result "
        f"| IP={result['ip']} | Score={result['score']} | Country={result['country']} "
        f"| LastReported={result['lastReportedAt']} | TotalReports={result['totalReports']} "
        f"| Status={status} | ElapsedTime={result['elapsedTime']:.3f}s "
        f"| ReportPath={report_path if report_path else 'None'}"
    )


def listen_and_process():
    """Listen for UDP messages, enrich IPs, and forward results to QRadar."""
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("0.0.0.0", LISTEN_PORT))
    sock.settimeout(1.0)

    send_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    print(f"[*] Listening for UDP on port {LISTEN_PORT}...")

    try:
        while True:
            try:
                data, addr = sock.recvfrom(4096)
            except socket.timeout:
                continue

            try:
                message = data.decode("utf-8", errors="replace")
                print(f"[*] Received from {addr}: {message}")

                match = IP_REGEX.search(message)
                if not match:
                    continue

                ip = match.group(1)
                print(f"[*] Checking {ip} in AbuseIPDB...")

                result = query_abuseipdb(ip)
                print(f"[+] Result: {result}")

                status = classify_status(result["score"], result["totalReports"])

                report_path = None
                if status in {"High-Risk", "Medium-Risk"}:
                    report_path = generate_pdf_report(
                        result["ip"],
                        result["score"],
                        result["country"],
                        result["lastReportedAt"],
                        result["totalReports"],
                        status,
                    )

                syslog_msg = format_syslog(result, report_path)
                print(f"[*] Sending enriched event to QRadar: {syslog_msg}")
                send_sock.sendto(
                    syslog_msg.encode("utf-8"),
                    (QRADAR_IP, QRADAR_PORT),
                )

            except Exception as exc:
                print(f"[!] Processing error: {exc}")

    except KeyboardInterrupt:
        print("\n[!] Script interrupted. Cleaning up...")
    finally:
        sock.close()
        send_sock.close()
        print("[*] Exited cleanly.")


if __name__ == "__main__":
    listen_and_process()
